# Generated by Django 6.0.2 on 2026-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_delete_resource'),
        ('mockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockresource',
            name='access_role',
            field=models.ManyToManyField(blank=True, to='access.role'),
        ),
    ]
