# Generated by Django 6.0.2 on 2026-02-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(blank=True, related_name='role_permissions', to='access.action')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.role')),
            ],
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
