# Generated by Django 6.0.2 on 2026-02-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_roleactions_delete_rolepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleActions',
            new_name='RoleAction',
        ),
    ]
