# Generated by Django 6.0.2 on 2026-02-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_rename_roleactions_roleaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
