# Generated by Django 6.0.2 on 2026-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_delete_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
