# Generated by Django 6.0.2 on 2026-02-21 14:10

from django.db import migrations, models


def normalize_actions(apps, schema_editor):
    Action = apps.get_model("access", "Action")
    allowed_codes = {"read", "create", "update", "delete"}

    Action.objects.exclude(code__in=allowed_codes).delete()
    for code in allowed_codes:
        Action.objects.get_or_create(code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_role_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=50, unique=True),
        ),
        migrations.RunPython(normalize_actions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ['read', 'create', 'update', 'delete'])), name='access_action_code_valid'),
        ),
    ]
