# Generated by Django 6.0.2 on 2026-02-21 14:13

import access.models
from django.db import migrations, models


def copy_actions_to_action_codes(apps, schema_editor):
    RoleAction = apps.get_model("access", "RoleAction")

    for role_action in RoleAction.objects.all():
        role_action.action_codes = list(
            role_action.actions.values_list("code", flat=True)
        )
        role_action.save(update_fields=["action_codes"])


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_remove_action_name_alter_action_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleaction',
            name='action_codes',
            field=models.JSONField(blank=True, default=list, validators=[access.models.validate_action_codes]),
        ),
        migrations.RunPython(copy_actions_to_action_codes, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='action',
            name='access_action_code_valid',
        ),
        migrations.RemoveField(
            model_name='roleaction',
            name='actions',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
